name: gentleroom
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bootstrap: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  freezed: ^2.3.4
  json_serializable: ^6.1.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: RenogareSoft
      fonts:
        - asset: assets/fonts/RenogareSoft-Regular.ttf
          style: normal

